
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - courses
    - currentSEID
    - divisions
    - division_chair
    - division_to_program
    - programs
    - program_chair
    - role
    - semester
    - syllabus
    - syllabus_course_semester
    - uscs
    - users
    - user_role
# this makes the navigation bar
mainMenu:
  #- title: "Home"
  #  link: "/"
  #- title: "Program Display"
  #  link: "readPrograms"
  #- title: "Course Display"
  #  link: "readCourses"
  #- title: "Relational Table"
  #  link: "aRelationalTable"
