
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Semesters
    - Divisions
    - Programs
    - Users
    - Courses
    - UsersCourses
    - Deadline
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/courses"
  - title: "Archive"
    link: "/archive"
    
adminMenu:
  Administration:
    - title: "Program Management"
      link:  "/redirect/program_management"
    - title: "Division Management"
      link:  "/redirect/division_management"
    - title: "System Management"
      link:  "/admin/systemManagement"
    
Headers:
  Courses: ['Instructor','Course','Term','Syllabus Action','Last Modified By']
  Archive: ['Instructor','Course','Term','Last Modified By']
    
fileOperations:
  allowedExtension:
      pdf: "pdf"
      doc: "doc"
      docx: "docx"
  allowedSize:
      size: 8000000
  dataPaths:
      uploads: "static/files/uploads"
      zips: "static/files/zips"
      temp: "static/files/tmp"
  
DEBUG:
  user: "heggens" #Admin Access
  # user: "pearcej" #Division Chair Access
  # user: "jadudm"  #Professor Access
  # user: "nakazawam" #Program Access