
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Semesters
    - Divisions
    - Programs
    - Users
    - Courses
    - UsersCourses
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/courses"
  - title: "Syllabi Archive"
    link: "/archive"
    
fileOperations:
  allowedExtension:
      pdf: "pdf"
      doc: "doc"
      docx: "docx"
  allowedSize:
      size: 8000000
  dataPaths:
      uploads: "static/files/uploads"
      zips: "static/files/zips"
      temp: "static/files/tmp"
  
DEBUG:
  user: "heggens" #Admin Access
  # user: "pearcej" #Division Chair Access
  # user: "jadudm"  #Program Chair Access
  # user: "myersco" #Professor Access