
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: "data/bcsr.sqlite"

databaseAdmin:
  user: 'heggens'
  
# For every table in the database, add an item here
models:
  mainDB:
    - Semesters
    - Divisions
    - Programs
    - Users
    - Courses
    - UsersCourses
    - Deadline
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "/courses"
  - title: "Archive"
    link: "/archive"
  - title: "Log Out"
    link: "https://login.berea.edu/idp/profile/Logout"
    
adminMenu:
  Administration:
    - title: "Program Management"
      link:  "/redirect/program_management"
    - title: "Division Management"
      link:  "/redirect/division_management"
    - title: "System Management"
      link:  "/admin/systemManagement"
    - title: "Course Management"
      link:  "/admin/courseManagement/missingSyllabi"

courseManagementSidebar:
  - title: "Missing Syllabi"
    link:  "/admin/courseManagement/missingSyllabi"
  - title: "Add Course"
    link: "/admin/courseManagement/addCourse"
  - title: "Remove Course"
    link: "/admin/courseManagement/removeCourse"
    
Headers:
  Courses: ['Instructor','Course','Term','Syllabus Upload','Last Modified By']
  Archive: ['Instructor','Course','Term','Last Modified By']
    
fileOperations:
  allowedExtension:
      pdf: "pdf"
      doc: "doc"
      docx: "docx"
  allowedSize:
      size: 8000000
  dataPaths:
      uploads: "app/static/files/uploads"
      zips: "static/files/zips"
      tmp: "app/static/files/tmp"
      download: "static/files/uploads"

termInfo:
#the keys correlate to the last two digits in the term code eg: Fall 2016 = 201611 
    11: 'Fall'              # e.g. Fall 2016 = 201611
    12: 'Spring'            # e.g. Spring 2017 = 201612 (note the different year)
    13: 'Summer'            
    #NOTE: Scott Steele asked us to replace the 3 summer terms with just summer 20180612
    #13: '8 Week Summer'     # e.g. 8 Week Summer 2017 = 201613 (note the different year)
    #14: '1st 4 Week Summer'
    #15: '2nd 4 Week Summer'
    #10: 'Berea Bridge Program'   # e.g. Berea Bridge Program 2016 = 201610 
    
DEBUG:
  user: "HEGGENS@berea.edu" #Admin Access
  # user: "pearcej" #Division Chair Access
  # user: "jadudm"  #Professor Access
  # user: "nakazawam" #Program Access
  
contributors:
  - name: "Cody Myers"
    username: "myersco"
    year: 2017
  - name: "Guillermo Ramos"
    username: "ramosg"
    year: 2018
  - name: "Sarah Watts"
    username: "wattss"
    year: 2018
  - name: "Jose Zindia"
    username: "zindiaj"
    year: 2018
  - name: "Jonathan Chauwa"
    username: "chauwaj"
    year: 2019
  - name: "Kenny Nelson"
    username: "nelsonk"
    year: 2019
  - name: "Sher Sanginov"
    username: "sanginovs"
    year: 2019
  - name: "Evan Johnson"
    username: "johnsone"
    year: 2019

  
    
    
