
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Courses
    - CurrentSemester
    - Divisions
    - DivisionChair
    - DivisionToProgram
    - Programs
    - ProgramChair
    - Role
    - Semester
    - Syllabus
    - SyllabusCourseSemester
    - UsersToSCS
    - Users
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "courses"