
# The log file location   
log:
filename: "bcsr.log"

# All the databases used by the system
databases:
  dev: "data/bcsr.sqlite"
  stage: ""
  prod: ""

# For every table in the database, add an item here
models:
  mainDB:
    - Semesters
    - Divisions
    - Programs
    - Users
    - Courses
# this makes the navigation bar
mainMenu:
  - title: "Home"
    link: "/"
  - title: "Courses"
    link: "courses"